kind: Service
apiVersion: v1
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  clusterIP: 10.254.200.120
  ports:
    - port: 27017
      targetPort: mongo
  selector:
    name: mongo
    role: mongo
