apiVersion: v1
kind: Service
metadata:
  labels:
    app: rocketchat
  name: rocketchat
spec:
  type: "LoadBalancer"
  ports:
    - port: 3000
      name: rocketchat
      targetPort: 3000
      nodePort: 30880
  selector:
    app: rocketchat
