apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv5gjenkins
  labels:
    app: jenkins
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/jenkins_home
    server: 10.90.0.23
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvcjenkins
  labels:
    app: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
