apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv5gacmeapache
  labels:
    app: acmeapache
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/acme_web/apache
    server: 10.90.0.23
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvcacmeapache
  labels:
    app: acmeapache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv5gacmehtml
  labels:
    app: acmehtml
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/acme_web/html
    server: 10.90.0.23
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvcacmehtml
  labels:
    app: acmehtml
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi