apiVersion: v1
kind: ReplicationController
metadata:
  name: concrete5
  labels:
    app: concrete5
spec:
  replicas: 1
  # selector:
      # app: concrete5
  template:
    metadata:
      labels:
        app: concrete5
    spec:
      containers:
        - resources:
            limits:
              cpu: 0.1
          # local copy of docker.io/chriswayg/concrete5.7
          image: kube-master:5000/concrete5.7
          name: concrete5
          ports:
            - containerPort: 80
              name: concrete5-80
            - containerPort: 443
              name: concrete5-443
          volumeMounts:
            # name must match the volume name below
            - name: acme-apache
              # mount path within the container
              mountPath: /etc/apache2
            - name: acme-html
              # mount path within the container
              mountPath: /var/www/html

      volumes:
        - name: acme-apache
          persistentVolumeClaim:
           claimName: pvcacmeapache
        - name: acme-html
          persistentVolumeClaim:
           claimName: pvcacmehtml